connectionId: jobConfigConnection
job:
  stream: loaderJobStream
  configSet: loaderJobConfigs
  completedJobsSet: loadercompletedJobs
  consumerGroup: loaderJobGroup
  jobConfig:
    - name: batchtaskcreator
      config: TaskCreator.yml
      variables:
        connectionProvider: GemfireConnectionProvider
        connectionId: gemfireConnection
   


        




